fix: walkthrough titles throughout
curiousways/marketdesign pull request #56
Opened 2022-11-25 21:17 UTC by alexandermendes

<img width="554" alt="image" src="https://user-images.githubusercontent.com/5636273/204055863-2f17fc3d-e39a-4065-88ca-ed78094f50da.png">

<img width="518" alt="image" src="https://user-images.githubusercontent.com/5636273/204055877-2ea7c1a0-a9d7-4bfd-927e-65c3779c349f.png">

<img width="484" alt="image" src="https://user-images.githubusercontent.com/5636273/204055897-1e71a559-e4bf-455e-a014-bf0f7c729c52.png">

That walkthrough number is actually an index that is directly related to how we lookup the data, which would be a hassle to change, so let's hope they don't notice/mind that the slug in the URL is still `generic-1-1` for the intro walkthrough (they haven't so far from the feedback) 😉

2022-11-26 11:48 UTC, curiousways requested changes
The index page Walkthrough 0 is titled as "Walkthrough 1"
<img width="605" alt="Screenshot 2022-11-26 at 11 46 35" src="https://user-images.githubusercontent.com/71117886/204087180-f000b94a-e31c-4ab4-b5a1-8ecbc3cc97ce.png">

2022-11-26 12:27 UTC, alexandermendes commented
Oops, well spotted, thanks

2022-11-26 12:32 UTC, curiousways commented
also forgot to say, the URLs will be fine exactly as they are

2022-11-27 05:33 UTC, curiousways approved these changes

2022-11-27 05:34 UTC, merged